project:
  type: website
  output-dir: docs

website:
  title: "Demi_Yang - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly notes"
        menu:
          - href: weekly-notes/
            text: "All notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4"
      - text: "Labs"
        menu: 
          - href: labs/lab_0/lab0_template.qmd
            text: "Lab 0: dplyr Basics"
      - text: "Assignments"
        menu: 
          - href: assignments/assignment_1/assignment1_CensusDataExploration.qmd
            text: "Assignment 1: Census Data Explorations"
          - href: assignments/assignment_2/assignment2_SpatialAnalysisAndVisualization.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: assignments/assignment_4/Assignment4_SpatialPredictiveAnalysis.qmd
            text: "Assignment 4: Spatial Predictive Analysis"
          - href: assignments/assignment_5/Assignment5_SpaceTimePrediction.qmd
            text: "Assignment 5: Space Time Prediction"
      - text: "Mid-term"
        menu: 
          - href: midterm/appendix/Yuqing_Yang_appendix.qmd
            text: "Appendix: Residential Sale Price Prediction" 
          - href: midterm/slides/Yuqing_Yang_Presentation.qmd
            text: "Slides: Residential Sale Price Prediction"
      - text: "Final"
        menu: 
          - href: final/Final_appendix.qmd
            text: "Appendix: Crime Count Prediction" 
          - href: final/Slides/Simple.qmd
            text: "Slide: Crime Count Prediction" 
          
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

